### PR TITLE
Fixes container not being executed

### PR DESCRIPTION
**Pull request by bibaldo**

### CODE REVIEW

**Comment by pablokbs** [comment]
Esto lo arregla? Rarisimo que a mi me ande sin eso

**Comment by bibaldo** [comment]
habria que probarlo con una instalacion de 0

**Comment by ddiaz2380** [comment]
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'flexget' failed to build: The command '/bin/sh -c apk add --update   tzdata   python   py-pip   ca-certificates   && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11   && rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by pablokbs** [comment]
Cerrando porque no usamos mas rtorrent

**Pull request closed without merging**
